"""initial schema

Revision ID: fa3c37b283d7
Revises: 
Create Date: 2026-09-24 10:14:44.381663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa3c37b283d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('ice_number', sa.String(length=15), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('settings_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ice_number')
    )
    op.create_table('cylinder_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('gas_type', sa.String(length=20), nullable=False),
    sa.Column('size_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('deposit_amount_mad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_sale_price_mad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gas_type IN ('butane','propane')", name='ck_cylinder_gas_type'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'gas_type', 'size_kg', name='uq_cylinder_tenant_gas_size')
    )
    op.create_index(op.f('ix_cylinder_types_tenant_id'), 'cylinder_types', ['tenant_id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_idem_tenant_key')
    )
    op.create_table('inventory_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('depot','vehicle','outlet','quarantine')", name='ck_location_type'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_locations_tenant_id'), 'inventory_locations', ['tenant_id'], unique=False)
    op.create_table('outlets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('geofence_radius_m', sa.Integer(), nullable=False),
    sa.Column('credit_limit_mad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('geofence_radius_m BETWEEN 30 AND 200', name='ck_outlets_radius'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outlets_tenant_id'), 'outlets', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('preferred_lang', sa.String(length=5), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("preferred_lang IN ('fr','ar')", name='ck_users_lang'),
    sa.CheckConstraint("role IN ('owner','dispatcher','warehouse','agent','accountant','auditor')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'phone', name='uq_users_tenant_phone')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('max_payload_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'plate_number', name='uq_vehicles_tenant_plate')
    )
    op.create_index(op.f('ix_vehicles_tenant_id'), 'vehicles', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_entity', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('credit_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('issued_by', sa.UUID(), nullable=False),
    sa.Column('override_code', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('override_code')
    )
    op.create_index(op.f('ix_credit_overrides_outlet_id'), 'credit_overrides', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_credit_overrides_tenant_id'), 'credit_overrides', ['tenant_id'], unique=False)
    op.create_table('driver_shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('depot_location_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('pre_trip_safety_passed', sa.Boolean(), nullable=False),
    sa.Column('pre_trip_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('odometer_km', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('declared_cash_mad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','RECONCILED','VARIANCE_FLAGGED','CLOSED')", name='ck_shift_status'),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['depot_location_id'], ['inventory_locations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_shifts_agent_id'), 'driver_shifts', ['agent_id'], unique=False)
    op.create_index(op.f('ix_driver_shifts_tenant_id'), 'driver_shifts', ['tenant_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cylinder_type_id', sa.UUID(), nullable=False),
    sa.Column('cylinder_state', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('from_location_id', sa.UUID(), nullable=True),
    sa.Column('to_location_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('client_event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cylinder_state IN ('full','empty','defective')", name='ck_inv_state'),
    sa.CheckConstraint('quantity > 0', name='ck_inv_qty_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cylinder_type_id'], ['cylinder_types.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['inventory_locations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_location_id'], ['inventory_locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'client_event_id', name='uq_inv_mvmt_tenant_client_event')
    )
    op.create_index(op.f('ix_inventory_movements_occurred_at'), 'inventory_movements', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_inventory_movements_tenant_id'), 'inventory_movements', ['tenant_id'], unique=False)
    op.create_table('media_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('media_token', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_token')
    )
    op.create_index(op.f('ix_media_objects_tenant_id'), 'media_objects', ['tenant_id'], unique=False)
    op.create_table('cash_handovers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('cashier_user_id', sa.UUID(), nullable=False),
    sa.Column('expected_cash_mad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('declared_cash_mad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('verified_cash_mad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('variance_mad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('variance_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DECLARED','HANDED_OVER','VERIFIED','VARIANCE_FLAGGED')", name='ck_handover_status'),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cashier_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['driver_shifts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_handovers_shift_id'), 'cash_handovers', ['shift_id'], unique=False)
    op.create_index(op.f('ix_cash_handovers_tenant_id'), 'cash_handovers', ['tenant_id'], unique=False)
    op.create_table('load_sheets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('depot_location_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('client_event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING_ACCEPT','ACCEPTED','VOID')", name='ck_load_status'),
    sa.ForeignKeyConstraint(['depot_location_id'], ['inventory_locations.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['driver_shifts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['warehouse_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_event_id')
    )
    op.create_index(op.f('ix_load_sheets_tenant_id'), 'load_sheets', ['tenant_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('planned_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('dispatcher_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','PUBLISHED','IN_PROGRESS','COMPLETED')", name='ck_route_status'),
    sa.ForeignKeyConstraint(['dispatcher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['driver_shifts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_shift_id'), 'routes', ['shift_id'], unique=False)
    op.create_index(op.f('ix_routes_tenant_id'), 'routes', ['tenant_id'], unique=False)
    op.create_table('safety_incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=False),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('photo_media_token', sa.String(length=255), nullable=True),
    sa.Column('cylinder_type_id', sa.UUID(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('LOW','HIGH','CRITICAL')", name='ck_incident_severity'),
    sa.ForeignKeyConstraint(['cylinder_type_id'], ['cylinder_types.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['driver_shifts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_incidents_shift_id'), 'safety_incidents', ['shift_id'], unique=False)
    op.create_index(op.f('ix_safety_incidents_tenant_id'), 'safety_incidents', ['tenant_id'], unique=False)
    op.create_table('load_sheet_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('load_sheet_id', sa.UUID(), nullable=False),
    sa.Column('cylinder_type_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cylinder_type_id'], ['cylinder_types.id'], ),
    sa.ForeignKeyConstraint(['load_sheet_id'], ['load_sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_method', sa.String(length=20), nullable=True),
    sa.Column('arrival_distance_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('exception_reason', sa.String(length=50), nullable=True),
    sa.Column('assigned_agent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("arrival_method IS NULL OR arrival_method IN ('geofence','manual_proximity','supervisor_override')", name='ck_arrival_method'),
    sa.CheckConstraint("status IN ('PENDING','EN_ROUTE','NEARBY','ARRIVED','IN_SERVICE','COMPLETED','EXCEPTION')", name='ck_stop_status'),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'sequence_order', name='uq_route_stop_seq')
    )
    op.create_index(op.f('ix_route_stops_outlet_id'), 'route_stops', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    op.create_index(op.f('ix_route_stops_tenant_id'), 'route_stops', ['tenant_id'], unique=False)
    op.create_table('delivery_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('route_stop_id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('recipient_name', sa.String(length=100), nullable=False),
    sa.Column('signature_media_token', sa.String(length=255), nullable=True),
    sa.Column('photo_media_token', sa.String(length=255), nullable=True),
    sa.Column('subtotal_mad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_net_mad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount_mad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('client_event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['route_stop_id'], ['route_stops.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['driver_shifts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'client_event_id', name='uq_dn_tenant_client_event'),
    sa.UniqueConstraint('tenant_id', 'receipt_number', name='uq_dn_tenant_receipt')
    )
    op.create_index(op.f('ix_delivery_notes_outlet_id'), 'delivery_notes', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_delivery_notes_route_stop_id'), 'delivery_notes', ['route_stop_id'], unique=False)
    op.create_index(op.f('ix_delivery_notes_tenant_id'), 'delivery_notes', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('route_stop_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('amount_mad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('client_event_id', sa.UUID(), nullable=False),
    sa.Column('handover_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("handover_status IN ('COLLECTED','DECLARED','HANDED_OVER','VERIFIED')", name='ck_pay_handover'),
    sa.CheckConstraint("method IN ('cash','check','bank_transfer','mobile_wallet')", name='ck_pay_method'),
    sa.CheckConstraint('amount_mad > 0', name='ck_pay_amount_positive'),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['route_stop_id'], ['route_stops.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['driver_shifts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'client_event_id', name='uq_pay_tenant_client_event'),
    sa.UniqueConstraint('tenant_id', 'receipt_number', name='uq_pay_tenant_receipt')
    )
    op.create_index(op.f('ix_payments_outlet_id'), 'payments', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_table('delivery_note_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_note_id', sa.UUID(), nullable=False),
    sa.Column('cylinder_type_id', sa.UUID(), nullable=False),
    sa.Column('delivered_full_qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('returned_empty_qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('returned_defective_qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('applied_unit_price_mad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('applied_deposit_rate_mad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_total_mad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cylinder_type_id'], ['cylinder_types.id'], ),
    sa.ForeignKeyConstraint(['delivery_note_id'], ['delivery_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_note_lines_delivery_note_id'), 'delivery_note_lines', ['delivery_note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_note_lines_delivery_note_id'), table_name='delivery_note_lines')
    op.drop_table('delivery_note_lines')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_outlet_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_delivery_notes_tenant_id'), table_name='delivery_notes')
    op.drop_index(op.f('ix_delivery_notes_route_stop_id'), table_name='delivery_notes')
    op.drop_index(op.f('ix_delivery_notes_outlet_id'), table_name='delivery_notes')
    op.drop_table('delivery_notes')
    op.drop_index(op.f('ix_route_stops_tenant_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_outlet_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_table('load_sheet_lines')
    op.drop_index(op.f('ix_safety_incidents_tenant_id'), table_name='safety_incidents')
    op.drop_index(op.f('ix_safety_incidents_shift_id'), table_name='safety_incidents')
    op.drop_table('safety_incidents')
    op.drop_index(op.f('ix_routes_tenant_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_shift_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_load_sheets_tenant_id'), table_name='load_sheets')
    op.drop_table('load_sheets')
    op.drop_index(op.f('ix_cash_handovers_tenant_id'), table_name='cash_handovers')
    op.drop_index(op.f('ix_cash_handovers_shift_id'), table_name='cash_handovers')
    op.drop_table('cash_handovers')
    op.drop_index(op.f('ix_media_objects_tenant_id'), table_name='media_objects')
    op.drop_table('media_objects')
    op.drop_index(op.f('ix_inventory_movements_tenant_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_occurred_at'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_driver_shifts_tenant_id'), table_name='driver_shifts')
    op.drop_index(op.f('ix_driver_shifts_agent_id'), table_name='driver_shifts')
    op.drop_table('driver_shifts')
    op.drop_index(op.f('ix_credit_overrides_tenant_id'), table_name='credit_overrides')
    op.drop_index(op.f('ix_credit_overrides_outlet_id'), table_name='credit_overrides')
    op.drop_table('credit_overrides')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_vehicles_tenant_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_outlets_tenant_id'), table_name='outlets')
    op.drop_table('outlets')
    op.drop_index(op.f('ix_inventory_locations_tenant_id'), table_name='inventory_locations')
    op.drop_table('inventory_locations')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_cylinder_types_tenant_id'), table_name='cylinder_types')
    op.drop_table('cylinder_types')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
